server:
  port: 8093

# thread pool config
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy


# dynamic thread pool config
dynamic:
  thread:
    pool:
      redis:
        config:
          enabled: true
          # redis host
          host: 127.0.0.1
          # redis port
          port: 16379
      zookeeper:
        config:
          connect-string: 127.0.0.1:2181
          base-sleep-time-ms: 1000
          max-retries: 3
          session-timeout-ms: 1800000
          connection-timeout-ms: 30000


logging:
  level:
    root: info
  config: classpath:logback-spring.xml
